baseURL: https://shakthir.work/
languageCode: en-us
title: My Pictures

theme: "PaperMod"

outputs:
    home:
        - HTML
        - RSS
        - JSON
languages:
  en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10

  menu:
        main:
                - name: Archive
                  url: archives/
                  weight: 5
              #  - name: Tags
              #    url: tags
              #    weight: 10
                - name: Categories
                  url: categories
                  weight: 10
                - name: Series
                  url: series
                  weight: 10
              #  - name: NullLink
              #    url: "#"
              #  - name: NullLink2
              #    url: "#"
              #  - name: NullLink3
              #    url: "#"

params:
    defaultTheme: auto
    homeInfoParams:
        Title: Hi there
        Content: My name's Shakthi Rajesh and welcome to my site.
                 I'm an amateur photographer and animal enthusiast. I created this site to show off some of my images and tell you a little bit about the animals in each one.

    socialIcons:
        #- name: "github"
        #    url: "<link>"
      #  - name: "<platform 2>"
      #      url: "<link2>"
